<?php
	//LSD Hosting - www.LSD-HOSTING.info

	$obaveštenja = 'Pročitajte važno <a href="obavjest.php">obavještenje</a> vezano za hosting..'; //Akcije
	$obaveštenje = 'Ovaj sajt je samo zamena, kako sajt tako i gpanel...LSD Hosting priprema za vas gaming hosting sajt sa intengriranim gpanel-om, izrade su u toku..Kontaktirajte nas preko email-a (lsdhosting@gmail.com) dok naš CMS bude gotov..Podrška za naše klijente će biti dostupna na našoj <a href="https://www.facebook.com/HostingFNT" target="_blank">Facebook</a> stranici, tu nas možete pitati u vezi problema sa vašim serverom...'; //Obavještenje
	$tel = '+387 61 076 471'; //Telefon
	$zakupiopis = 'Naši serveri se hostaju na 4 Core mašinama sa 16GB rama. Lokacija naših servera je smještena u Njemačkoj, samim tim pruža adekvatnu igru na vašem serveru. Svi naši serveri su bazirani na CentOS - Linux sistemima... Naš zadatak jeste da pružimo što bolju uslugu našim korisnicima, te što bolji odaziv servera. Ukoliko se odlučite za SA-MP server 100+ slotova, moći će te postavljati pitanja podršci vezana za skriptanje. LSD Hosting nudi podršku korisnicima 24/7. Svi naši klijenti mogu biti sigurni da će naš tim da odgovora na sva pitanja i da vam pomogne da riješite svaki problem.';
	$obavjestenja1 = 'Naš hosting ima namjeru da napravi CMS sa intengriranim GPanelom za lakšu upotrebu korisnicima..Već smo bili uradili neke stvari, međutim mislimo da je predviđeni sajt previše dark te se ne uklapa fino..Zbog toga template je na prodaji, dobijete PSD fajlove i kodiran sajt...Više o tome možete pronaći <a href="http://rloveutionart.deviantart.com/art/Game-Hosting-Design-by-rloveution-FOR-SALE-448027979" target="_blank">ovdje</a>. Cijena: 20 € (samo Srbija & BiH)';
	$obavjestenja2 = 'Naši serveri se hostaju na 4 Core mašinama sa 8GB rama. Lokacija naših servera je smještena u Njemačkoj, samim tim pruža adekvatnu igru na vašem serveru. Svi naši serveri su bazirani na CentOS - Linux sistemima... Naš zadatak jeste da pružimo što bolju uslugu našim korisnicima, te što bolji odaziv servera. Ukoliko se odlučite za SA-MP server 100+ slotova, moći će te postavljati pitanja podršci vezana za skriptanje. LSD Hosting nudi podršku korisnicima 24/7. Svi naši klijenti mogu biti sigurni da će naš tim da odgovora na sva pitanja i da vam pomogne da riješite svaki problem. Od sada imam u ponudi i web hosting koji se hostaju na mašini od 16GB rama.. U planu nam je da uvedemo prodaju domena.<br /><br />Vaš LSD Hosting<br />www.LSD-HOSTING.info';
	$webserveri = 'Naši serveri se hostaju na 4 Core mašinama sa 16GB rama. Lokacija naših servera je smještena u Francuskoj i Njemačkoj. Na našem web serveru možete ukljuciti SSH opciju za komuniciranje vaše mašine sa web serverom.. LSD Hosting nudi podršku korisnicima 24/7. Svi naši klijenti mogu biti sigurni da će naš tim da odgovora na sva pitanja i da vam pomogne da riješite svaki problem.';
?>